using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Nullean.Kerf;

/// <summary>
/// A parsed C# source file, held together with the original text so that printers can emit
/// spans of the source rather than allocating strings for every token.
/// </summary>
/// <remarks>
/// Kerf always parses at <see cref="LanguageVersion.Preview"/>: a formatter must never reject
/// syntax merely because it is newer than the formatter's own printers. Syntax it does not yet
/// understand is emitted verbatim instead.
/// </remarks>
public sealed class CSharpSource
{
	private CSharpSource(SourceText text, SyntaxNode root)
	{
		Text = text;
		Root = root;
	}

	/// <summary>The original source text. Text leaves in the document IR index into this.</summary>
	public SourceText Text { get; }

	/// <summary>The parsed compilation unit.</summary>
	public SyntaxNode Root { get; }

	private static readonly CSharpParseOptions ParseOptions = new(LanguageVersion.Preview);

	/// <summary>
	/// True when the file announces itself as generated in its opening comment.
	/// </summary>
	/// <remarks>
	/// <para>
	/// The convention Roslyn's analyzers, <c>dotnet format</c> and CSharpier all follow, and the only
	/// opt-out that needs no configuration at all — which matters, because a generated file's
	/// <c>.editorconfig</c> is usually not the generator's to edit.
	/// </para>
	/// <para>
	/// Read off the raw text rather than the tree: it decides whether to parse at all, and a file
	/// that says it is generated should cost one scan of its first few lines, not a parse. Only
	/// leading whitespace and comments are examined, so the marker has to be at the top; a mention
	/// of <c>&lt;auto-generated&gt;</c> further down is just a string.
	/// </para>
	/// </remarks>
	public static bool HasGeneratedHeader(ReadOnlySpan<char> source)
	{
		var index = 0;

		while (index < source.Length)
		{
			if (char.IsWhiteSpace(source[index]))
			{
				index++;
				continue;
			}

			if (source[index] != '/' || index + 1 >= source.Length)
				return false;

			var next = source[index + 1];
			int end;

			if (next == '/')
			{
				end = source[index..].IndexOfAny('\r', '\n');
				end = end < 0 ? source.Length : index + end;
			}
			else if (next == '*')
			{
				var close = source[(index + 2)..].IndexOf("*/", StringComparison.Ordinal);
				end = close < 0 ? source.Length : index + 2 + close + 2;
			}
			else
				return false;

			var comment = source[index..end];
			if (comment.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
				|| comment.Contains("<autogenerated", StringComparison.OrdinalIgnoreCase))
				return true;

			index = end;
		}

		return false;
	}

	/// <summary>Parses <paramref name="source"/>. Returns <c>false</c> if it does not compile.</summary>
	/// <remarks>
	/// Kerf refuses to format source with syntax errors. Roslyn's recovery would happily produce a
	/// tree, but re-printing from a guessed tree is exactly how a formatter destroys code.
	/// </remarks>
	public static bool TryParse(string source, out CSharpSource parsed, out IReadOnlyList<Diagnostic> errors)
	{
		var text = SourceText.From(source);
		var tree = CSharpSyntaxTree.ParseText(text, ParseOptions);
		var root = tree.GetRoot();

		var diagnostics = tree.GetDiagnostics()
			.Where(d => d.Severity == DiagnosticSeverity.Error)
			.ToArray();

		if (diagnostics.Length > 0)
		{
			parsed = null!;
			errors = diagnostics;
			return false;
		}

		parsed = new CSharpSource(text, root);
		errors = [];
		return true;
	}
}
