using System.IO.Abstractions.TestingHelpers;
using AwesomeAssertions;
using Nullean.Curb;
using Nullean.Curb.EditorConfig;

namespace Nullean.Curb.Tests.Options;

/// <summary>
/// The ways a file says it should not be formatted.
/// </summary>
/// <remarks>
/// All four are mechanisms .NET already defines, which is the whole point: Curb has no ignore file
/// and no ignore comment of its own, so there is nothing extra to learn and nothing that only works
/// with Curb. <c>dotnet format</c> has no ignore comment either — the region mechanism is
/// <c>#pragma warning disable IDE0055</c>, which Roslyn honours in Format Document.
/// </remarks>
public class OptOutTests
{
	private const string Root = "/repo";

	private static FormatOptions Bind(string editorConfig, string fileName = "Foo.cs")
	{
		var fs = new MockFileSystem();
		fs.AddFile($"{Root}/.editorconfig", new MockFileData(editorConfig));
		fs.AddFile($"{Root}/{fileName}", new MockFileData("class Foo { }"));

		return EditorConfigOptionsBinder.Bind(new CurbEditorConfig(fs).For($"{Root}/{fileName}"));
	}

	// ---- generated_code ---------------------------------------------------------------------------

	[Test]
	public async Task Generated_code_excludes_the_file()
	{
		Bind("root = true\n\n[*.cs]\ngenerated_code = true\n").Excluded.Should().BeTrue();
		await Task.CompletedTask;
	}

	[Test]
	public async Task Generated_code_can_be_scoped_to_a_glob()
	{
		const string config = "root = true\n\n[*.cs]\nindent_size = 4\n\n[*.g.cs]\ngenerated_code = true\n";

		Bind(config, "Widget.g.cs").Excluded.Should().BeTrue();
		Bind(config, "Widget.cs").Excluded.Should().BeFalse("only the glob asked to be skipped");
		await Task.CompletedTask;
	}

	[Test]
	public async Task Generated_code_false_is_not_an_exclusion()
	{
		Bind("root = true\n\n[*.cs]\ngenerated_code = false\n").Excluded.Should().BeFalse();
		await Task.CompletedTask;
	}

	// ---- dotnet_diagnostic.IDE0055.severity -------------------------------------------------------

	[Test]
	public async Task Turning_the_formatting_rule_off_excludes_the_file()
	{
		// EditorConfig lower-cases keys, so the rule id arrives as `ide0055` however it was written.
		Bind("root = true\n\n[*.cs]\ndotnet_diagnostic.IDE0055.severity = none\n").Excluded.Should().BeTrue();
		await Task.CompletedTask;
	}

	[Test]
	public async Task Any_other_severity_still_formats()
	{
		Bind("root = true\n\n[*.cs]\ndotnet_diagnostic.IDE0055.severity = warning\n").Excluded.Should().BeFalse();
		await Task.CompletedTask;
	}

	[Test]
	public async Task Another_rule_being_silenced_is_none_of_our_business()
	{
		Bind("root = true\n\n[*.cs]\ndotnet_diagnostic.IDE0059.severity = none\n").Excluded.Should().BeFalse();
		await Task.CompletedTask;
	}

	// ---- <auto-generated> ---------------------------------------------------------------------------

	[Test]
	[Arguments("// <auto-generated />\nclass C { }")]
	[Arguments("// <auto-generated>\n// Changes will be lost.\n// </auto-generated>\nclass C { }")]
	[Arguments("//     <autogenerated />\nclass C { }")]
	[Arguments("/* <auto-generated> */\nclass C { }")]
	[Arguments("\n\n// <AUTO-GENERATED />\nclass C { }")]
	public async Task A_generated_header_is_recognised(string source)
	{
		CSharpSource.HasGeneratedHeader(source).Should().BeTrue();
		await Task.CompletedTask;
	}

	[Test]
	[Arguments("class C { }")]
	[Arguments("// an ordinary comment\nclass C { }")]
	[Arguments("using System;\n// <auto-generated />\nclass C { }")]
	[Arguments("class C { const string S = \"<auto-generated>\"; }")]
	public async Task Anything_else_is_not_a_generated_header(string source)
	{
		// The marker has to head the file. Mentioned after code has started it is just a string, and
		// treating it otherwise would let a comment in the middle of a file silence the formatter.
		CSharpSource.HasGeneratedHeader(source).Should().BeFalse();
		await Task.CompletedTask;
	}

	// ---- per-file resolution ------------------------------------------------------------------------

	[Test]
	public async Task Options_are_resolved_per_file_not_per_directory()
	{
		// The reason this matters: options used to be cached per directory, so a file-scoped section
		// was applied or missed depending on which file sorted first. generated_code is exactly that
		// shape, so every mechanism above depended on this.
		const string config = "root = true\n\n[*.cs]\nindent_size = 4\n\n[Zebra.cs]\nindent_size = 2\n";

		var fs = new MockFileSystem();
		fs.AddFile($"{Root}/.editorconfig", new MockFileData(config));
		fs.AddFile($"{Root}/Alpha.cs", new MockFileData("class A { }"));
		fs.AddFile($"{Root}/Zebra.cs", new MockFileData("class Z { }"));

		var editorConfig = new CurbEditorConfig(fs);

		EditorConfigOptionsBinder.Bind(editorConfig.For($"{Root}/Alpha.cs")).IndentSize.Should().Be(4);
		EditorConfigOptionsBinder.Bind(editorConfig.For($"{Root}/Zebra.cs")).IndentSize.Should().Be(2);
		await Task.CompletedTask;
	}
}
