<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Nullean.Kerf.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Nullean.Kerf.Core/Nullean.Kerf.Core.csproj" />
    <ProjectReference Include="../../src/Nullean.Kerf.EditorConfig/Nullean.Kerf.EditorConfig.csproj" />
  </ItemGroup>

</Project>
