using System.Text;
using Nullean.Kerf;
using Nullean.Kerf.Options;

namespace Nullean.Kerf.OptionDocs;

/// <summary>
/// Generates docs/reference/options/**/*.md from OptionDescriptor.All by running
/// Kerf against each option's snippet fixture.
/// </summary>
internal static class Program
{
    // Walk up from the binary's location to find the repo root (the directory containing src/).
    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            if (Directory.Exists(Path.Combine(dir.FullName, "src")) &&
                Directory.Exists(Path.Combine(dir.FullName, "docs")))
                return dir.FullName;
            dir = dir.Parent;
        }
        throw new InvalidOperationException("Could not locate repo root from " + AppContext.BaseDirectory);
    }

    private static readonly string GroupedHeader = "<!-- generated by Nullean.Kerf.OptionDocs -->";

    private static readonly Dictionary<OptionGroup, string> GroupSlugs = new()
    {
        [OptionGroup.Core] = "core",
        [OptionGroup.NewLines] = "new-lines",
        [OptionGroup.Indentation] = "indentation",
        [OptionGroup.Spacing] = "spacing",
        [OptionGroup.Wrapping] = "wrapping",
        [OptionGroup.BlankLines] = "blank-lines",
        [OptionGroup.ExpressionBodies] = "expression-bodies",
        [OptionGroup.Usings] = "usings",
        [OptionGroup.ModifiersAndBraces] = "modifiers-and-braces",
        [OptionGroup.TrailingCommas] = "trailing-commas",
        [OptionGroup.Suppression] = "suppression",
    };

    private static readonly Dictionary<OptionGroup, string> GroupTitles = new()
    {
        [OptionGroup.Core] = "Core",
        [OptionGroup.NewLines] = "New Lines",
        [OptionGroup.Indentation] = "Indentation",
        [OptionGroup.Spacing] = "Spacing",
        [OptionGroup.Wrapping] = "Wrapping",
        [OptionGroup.BlankLines] = "Blank Lines",
        [OptionGroup.ExpressionBodies] = "Expression Bodies",
        [OptionGroup.Usings] = "Usings",
        [OptionGroup.ModifiersAndBraces] = "Modifiers and Braces",
        [OptionGroup.TrailingCommas] = "Trailing Commas",
        [OptionGroup.Suppression] = "Suppression",
    };

    internal static int Main(string[] args)
    {
        var root = RepoRoot();
        var outputRoot = Path.Combine(root, "docs", "reference", "options");

        Console.WriteLine($"repo root: {root}");
        Console.WriteLine($"output:    {outputRoot}");

        var formatter = new CSharpFormatter();
        var defaultOptions = new FormatOptions();

        var grouped = OptionDescriptor.All
            .GroupBy(d => d.Group)
            .ToDictionary(g => g.Key, g => g.ToList());

        // Write every option page.
        int generated = 0;
        foreach (var descriptor in OptionDescriptor.All)
        {
            var slug = GroupSlugs[descriptor.Group];
            var dir = Path.Combine(outputRoot, slug);
            Directory.CreateDirectory(dir);

            var snippet = Snippets.All.TryGetValue(descriptor.SnippetKey, out var s)
                ? s
                : throw new InvalidOperationException($"Missing snippet '{descriptor.SnippetKey}' for key '{descriptor.Key}'");

            var page = BuildPage(descriptor, snippet, formatter, defaultOptions);
            var path = Path.Combine(dir, descriptor.Key + ".md");
            File.WriteAllText(path, page, Encoding.UTF8);
            Console.WriteLine($"  {Path.GetRelativePath(root, path)}");
            generated++;
        }

        // Write group index pages.
        foreach (var (group, descriptors) in grouped)
        {
            var slug = GroupSlugs[group];
            var title = GroupTitles[group];
            var dir = Path.Combine(outputRoot, slug);
            Directory.CreateDirectory(dir);

            var sb = new StringBuilder();
            sb.AppendLine(GroupedHeader);
            sb.AppendLine("---");
            sb.AppendLine($"title: {title}");
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine($"# {title}");
            sb.AppendLine();
            sb.AppendLine($"{descriptors.Count} option{(descriptors.Count == 1 ? "" : "s")} in this group.");
            sb.AppendLine();
            sb.AppendLine("| Key | Default | Summary |");
            sb.AppendLine("|---|---|---|");
            foreach (var d in descriptors)
                sb.AppendLine($"| [{d.Key}]({d.Key}.md) | `{d.Default}` | {d.Summary} |");

            var path = Path.Combine(dir, "index.md");
            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            Console.WriteLine($"  {Path.GetRelativePath(root, path)}");
        }

        // Write the top-level options index.
        {
            Directory.CreateDirectory(outputRoot);
            var sb = new StringBuilder();
            sb.AppendLine(GroupedHeader);
            sb.AppendLine("---");
            sb.AppendLine("title: Option Reference");
            sb.AppendLine("---");
            sb.AppendLine();
            sb.AppendLine("# Option Reference");
            sb.AppendLine();
            sb.AppendLine($"Kerf implements {OptionDescriptor.All.Count} `.editorconfig` keys. Every key has a before/after example generated by running Kerf.");
            sb.AppendLine();
            sb.AppendLine("Use the filter above to search by name. Each group below links to its own index.");
            sb.AppendLine();
            foreach (var (group, descriptors) in grouped)
            {
                var slug = GroupSlugs[group];
                var title = GroupTitles[group];
                sb.AppendLine($"## [{title}]({slug}/index.md)");
                sb.AppendLine();
                foreach (var d in descriptors)
                    sb.AppendLine($"- [{d.Key}]({slug}/{d.Key}.md) — {d.Summary}");
                sb.AppendLine();
            }
            var path = Path.Combine(outputRoot, "index.md");
            File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
            Console.WriteLine($"  {Path.GetRelativePath(root, path)}");
        }

        Console.WriteLine($"\nDone. {generated} option pages written.");
        return 0;
    }

    private static string BuildPage(
        OptionDescriptor descriptor,
        string snippet,
        CSharpFormatter formatter,
        FormatOptions defaultOptions)
    {
        var slug = GroupSlugs[descriptor.Group];
        var sb = new StringBuilder();
        sb.AppendLine(GroupedHeader);
        sb.AppendLine("---");
        sb.AppendLine($"title: {descriptor.Key}");
        sb.AppendLine($"listing: {slug}");
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine($"# `{descriptor.Key}`");
        sb.AppendLine();
        sb.AppendLine(descriptor.Summary);
        sb.AppendLine();

        // Values table.
        sb.AppendLine("## Values");
        sb.AppendLine();
        sb.AppendLine("| Value | Notes |");
        sb.AppendLine("|---|---|");
        foreach (var v in descriptor.Values)
        {
            var note = v.StartsWith('<') && v.EndsWith('>') ? "Any integer." : "";
            sb.AppendLine($"| `{v}` | {note} |");
        }
        sb.AppendLine();
        sb.AppendLine($"**Default:** `{descriptor.Default}`");
        sb.AppendLine();

        // Format snippet with default options first (the "before").
        var defaultResult = formatter.Format(snippet, defaultOptions, produceText: true);
        var defaultFormatted = defaultResult.Success ? (defaultResult.Text ?? snippet) : snippet;

        // Examples section.
        sb.AppendLine("## Examples");
        sb.AppendLine();

        // Collect the iterable values (skip placeholder shapes like <integer>).
        var iterableValues = descriptor.Values
            .Where(v => !v.StartsWith('<') || !v.EndsWith('>'))
            .ToList();

        if (iterableValues.Count == 0)
        {
            sb.AppendLine("*This option accepts a freeform value. No canned example is generated.*");
            sb.AppendLine();
            sb.AppendLine("```editorconfig");
            sb.AppendLine($"{descriptor.Key} = <value>");
            sb.AppendLine("```");
        }
        else
        {
            sb.AppendLine("The snippet below is formatted with default options and then again with the option applied.");
            sb.AppendLine();
            sb.AppendLine("**Snippet (formatted with defaults):**");
            sb.AppendLine();
            sb.AppendLine("```csharp");
            sb.Append(defaultFormatted.TrimEnd());
            sb.AppendLine();
            sb.AppendLine("```");
            sb.AppendLine();

            foreach (var value in iterableValues)
            {
                sb.AppendLine($"### `{descriptor.Key} = {value}`");
                sb.AppendLine();
                sb.AppendLine("```editorconfig");
                sb.AppendLine($"{descriptor.Key} = {value}");
                sb.AppendLine("```");
                sb.AppendLine();

                var options = BuildOptions(descriptor, value);
                var result = formatter.Format(snippet, options, produceText: true);

                if (!result.Success)
                {
                    sb.AppendLine($"*Could not format: {result.Message}*");
                }
                else
                {
                    var output = result.Text ?? snippet;
                    if (output == defaultFormatted)
                    {
                        sb.AppendLine("*No visible change on this snippet — the option affects other constructs.*");
                    }
                    else
                    {
                        sb.AppendLine("```csharp");
                        sb.Append(output.TrimEnd());
                        sb.AppendLine();
                        sb.AppendLine("```");
                    }
                }
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Returns a <see cref="FormatOptions"/> that differs from the default in exactly one key.
    /// </summary>
    private static FormatOptions BuildOptions(OptionDescriptor d, string value)
    {
        var opts = new FormatOptions();
        bool b = value == "true";

        return d.Key switch
        {
            "indent_style" => opts with { UseTabs = value == "tab" },
            "insert_final_newline" => opts with { InsertFinalNewLine = b },
            "trim_trailing_whitespace" => opts with { TrimTrailingWhitespace = b },
            "end_of_line" => opts with
            {
                EndOfLine = value switch
                {
                    "lf" => EndOfLine.Lf,
                    "crlf" => EndOfLine.CrLf,
                    _ => EndOfLine.Auto,
                }
            },
            "charset" => opts with
            {
                Charset = value switch
                {
                    "utf-8" => Charset.Utf8,
                    "utf-8-bom" => Charset.Utf8Bom,
                    _ => Charset.Preserve,
                }
            },

            "csharp_new_line_before_else" => opts with { NewLineBeforeElse = b },
            "csharp_new_line_before_catch" => opts with { NewLineBeforeCatch = b },
            "csharp_new_line_before_finally" => opts with { NewLineBeforeFinally = b },
            "csharp_new_line_before_members_in_object_initializers" => opts with { NewLineBeforeMembersInObjectInitializers = b },
            "csharp_new_line_before_members_in_anonymous_types" => opts with { NewLineBeforeMembersInAnonymousTypes = b },
            "csharp_new_line_between_query_expression_clauses" => opts with { NewLineBetweenQueryExpressionClauses = b },

            "csharp_indent_case_contents" => opts with { IndentCaseContents = b },
            "csharp_indent_switch_labels" => opts with { IndentSwitchLabels = b },
            "csharp_indent_block_contents" => opts with { IndentBlockContents = b },
            "csharp_indent_braces" => opts with { IndentBraces = b },
            "csharp_indent_case_contents_when_block" => opts with { IndentCaseContentsWhenBlock = b },
            "csharp_indent_labels" => opts with
            {
                IndentLabels = value switch
                {
                    "flush_left" => LabelIndent.FlushLeft,
                    "no_change" => LabelIndent.NoChange,
                    _ => LabelIndent.OneLessThanCurrent,
                }
            },

            "csharp_space_after_cast" => opts with { SpaceAfterCast = b },
            "csharp_space_after_keywords_in_control_flow_statements" => opts with { SpaceAfterKeywordsInControlFlowStatements = b },
            "csharp_space_before_colon_in_inheritance_clause" => opts with { SpaceBeforeColonInInheritanceClause = b },
            "csharp_space_after_colon_in_inheritance_clause" => opts with { SpaceAfterColonInInheritanceClause = b },
            "csharp_space_around_binary_operators" => opts with
            {
                SpaceAroundBinaryOperators = value switch
                {
                    "none" => BinaryOperatorSpacing.None,
                    "ignore" => BinaryOperatorSpacing.Ignore,
                    _ => BinaryOperatorSpacing.BeforeAndAfter,
                }
            },
            "csharp_space_around_declaration_statements" => opts with
            {
                SpaceAroundDeclarationStatements = value switch
                {
                    "ignore" => DeclarationSpacing.Ignore,
                    _ => DeclarationSpacing.Normalise,
                }
            },
            "csharp_space_after_comma" => opts with { SpaceAfterComma = b },
            "csharp_space_before_comma" => opts with { SpaceBeforeComma = b },
            "csharp_space_between_parentheses" => opts with
            {
                SpaceBetweenParentheses = value switch
                {
                    "control_flow_statements" => ParenthesisSpacing.ControlFlowStatements,
                    "type_casts" => ParenthesisSpacing.TypeCasts,
                    "expressions" => ParenthesisSpacing.Expressions,
                    _ => ParenthesisSpacing.None,
                }
            },
            "csharp_space_between_method_declaration_parameter_list_parentheses" => opts with { SpaceInDeclarationParameterList = b },
            "csharp_space_between_method_declaration_empty_parameter_list_parentheses" => opts with { SpaceInEmptyDeclarationParameterList = b },
            "csharp_space_between_method_declaration_name_and_open_parenthesis" => opts with { SpaceBeforeDeclarationParameterList = b },
            "csharp_space_between_method_call_parameter_list_parentheses" => opts with { SpaceInCallArgumentList = b },
            "csharp_space_between_method_call_empty_parameter_list_parentheses" => opts with { SpaceInEmptyCallArgumentList = b },
            "csharp_space_between_method_call_name_and_opening_parenthesis" => opts with { SpaceBeforeCallArgumentList = b },
            "csharp_space_before_open_square_brackets" => opts with { SpaceBeforeOpenSquareBrackets = b },
            "csharp_space_between_empty_square_brackets" => opts with { SpaceBetweenEmptySquareBrackets = b },
            "csharp_space_between_square_brackets" => opts with { SpaceBetweenSquareBrackets = b },
            "csharp_space_before_dot" => opts with { SpaceBeforeDot = b },
            "csharp_space_after_dot" => opts with { SpaceAfterDot = b },
            "csharp_space_before_semicolon_in_for_statement" => opts with { SpaceBeforeSemicolonInForStatement = b },
            "csharp_space_after_semicolon_in_for_statement" => opts with { SpaceAfterSemicolonInForStatement = b },

            "csharp_preserve_single_line_blocks" => opts with { PreserveSingleLineBlocks = b },
            "csharp_preserve_single_line_statements" => opts with { PreserveSingleLineStatements = b },
            "csharp_keep_existing_linebreaks" => opts with { KeepExistingLinebreaksOption = b },
            "csharp_wrap_before_first_method_call" => opts with { WrapBeforeFirstMethodCall = b },
            "csharp_wrap_before_first_type_parameter_constraint" => opts with { WrapBeforeFirstTypeParameterConstraint = b },
            "csharp_wrap_before_extends_colon" => opts with { WrapBeforeExtendsColon = b },
            "csharp_place_constructor_initializer_on_same_line" => opts with { PlaceConstructorInitializerOnSameLine = b },
            "csharp_wrap_before_arrow_with_expressions" => opts with { WrapBeforeArrowWithExpressions = b },
            "csharp_wrap_after_dot_in_method_calls" => opts with { WrapAfterDotInMethodCalls = b },
            "csharp_place_simple_enum_on_single_line" => opts with { PlaceSimpleEnumOnSingleLine = b },
            "csharp_place_simple_accessorholder_on_single_line" => opts with { PlaceSimpleAccessorholderOnSingleLine = b },
            "csharp_wrap_before_binary_opsign" => opts with { WrapBeforeBinaryOpsign = b },
            "csharp_wrap_chained_binary_expressions" => opts with { WrapChainedBinaryExpressions = WrapStyle.ChopIfLong },
            "csharp_wrap_parameters_style" => opts with { WrapParametersStyle = value == "chop_always" ? WrapStyle.ChopAlways : WrapStyle.ChopIfLong },
            "csharp_wrap_arguments_style" => opts with { WrapArgumentsStyle = value == "chop_always" ? WrapStyle.ChopAlways : WrapStyle.ChopIfLong },
            "csharp_wrap_object_and_collection_initializer_style" => opts with { WrapObjectAndCollectionInitializerStyle = value == "chop_always" ? WrapStyle.ChopAlways : WrapStyle.ChopIfLong },
            "csharp_wrap_before_declaration_rpar" => opts with { WrapBeforeDeclarationRpar = b },
            "csharp_wrap_before_invocation_rpar" => opts with { WrapBeforeInvocationRpar = b },
            "csharp_place_method_attribute_on_same_line" => opts with { PlaceMethodAttributeOnSameLine = value == "if_owner_is_single_line" ? AttributePlacement.IfOwnerIsSingleLine : AttributePlacement.OwnLine },
            "csharp_place_field_attribute_on_same_line" => opts with { PlaceFieldAttributeOnSameLine = value == "if_owner_is_single_line" ? AttributePlacement.IfOwnerIsSingleLine : AttributePlacement.OwnLine },
            "csharp_place_property_attribute_on_same_line" => opts with { PlacePropertyAttributeOnSameLine = value == "if_owner_is_single_line" ? AttributePlacement.IfOwnerIsSingleLine : AttributePlacement.OwnLine },
            "csharp_place_event_attribute_on_same_line" => opts with { PlaceEventAttributeOnSameLine = value == "if_owner_is_single_line" ? AttributePlacement.IfOwnerIsSingleLine : AttributePlacement.OwnLine },

            "csharp_keep_blank_lines_in_declarations" => opts with { KeepBlankLinesInDeclarations = int.Parse(value) },
            "csharp_keep_blank_lines_in_code" => opts with { KeepBlankLinesInCode = int.Parse(value) },
            "csharp_blank_lines_around_invocable" => opts with { BlankLinesAroundInvocable = int.Parse(value) },
            "csharp_blank_lines_around_type" => opts with { BlankLinesAroundType = int.Parse(value) },
            "csharp_blank_lines_around_property" => opts with { BlankLinesAroundProperty = int.Parse(value) },
            "csharp_blank_lines_around_field" => opts with { BlankLinesAroundField = int.Parse(value) },
            "csharp_blank_lines_inside_type" => opts with { BlankLinesInsideType = int.Parse(value) },
            "csharp_blank_lines_around_namespace" => opts with { BlankLinesAroundNamespace = int.Parse(value) },
            "csharp_blank_lines_after_using_list" => opts with { BlankLinesAfterUsingList = int.Parse(value) },
            "csharp_blank_lines_after_file_scoped_namespace_directive" => opts with { BlankLinesAfterFileScopedNamespace = int.Parse(value) },

            "csharp_style_expression_bodied_methods" => opts with { ExpressionBodiedMethods = ParseExprBody(value) },
            "csharp_style_expression_bodied_constructors" => opts with { ExpressionBodiedConstructors = ParseExprBody(value) },
            "csharp_style_expression_bodied_operators" => opts with { ExpressionBodiedOperators = ParseExprBody(value) },
            "csharp_style_expression_bodied_local_functions" => opts with { ExpressionBodiedLocalFunctions = ParseExprBody(value) },
            "csharp_style_expression_bodied_accessors" => opts with { ExpressionBodiedAccessors = ParseExprBody(value) },
            "csharp_style_expression_bodied_properties" => opts with { ExpressionBodiedProperties = ParseExprBody(value) },
            "csharp_style_expression_bodied_indexers" => opts with { ExpressionBodiedIndexers = ParseExprBody(value) },

            "dotnet_sort_system_directives_first" => opts with { SortUsings = value == "true" ? UsingOrder.SystemFirst : UsingOrder.AsWritten },
            "dotnet_separate_import_directive_groups" => opts with { SeparateImportDirectiveGroups = b },
            "csharp_using_directive_placement" => opts with { UsingPlacement = value == "inside_namespace" ? UsingPlacement.InsideNamespace : UsingPlacement.OutsideNamespace },

            "csharp_prefer_braces" => opts with
            {
                PreferBraces = value switch
                {
                    "true" => BraceRequirement.Always,
                    "when_multiline" => BraceRequirement.WhenMultiline,
                    _ => BraceRequirement.AsWritten,
                }
            },
            "csharp_style_namespace_declarations" => opts with { NamespaceStyle = value == "file_scoped" ? NamespaceStyle.FileScoped : NamespaceStyle.AsWritten },

            "csharp_trailing_comma_in_multiline_lists" => opts with { TrailingCommaInMultilineLists = b },
            "csharp_trailing_comma_in_singleline_lists" => opts with { TrailingCommaInSinglelineLists = b },

            "generated_code" => opts with { Excluded = b },
            "dotnet_diagnostic.ide0055.severity" => value == "none" ? opts with { Excluded = true } : opts,

            // Keys with no runtime effect in FormatOptions (file_header_template, modifier order, max counts).
            "file_header_template" => opts with { FileHeaderTemplate = value },
            "csharp_preferred_modifier_order" => opts,
            "max_line_length" => value == "off" ? opts : opts with { MaxLineLength = int.TryParse(value, out var w) ? w : FormatOptions.Off },

            // Integer family — generate the page but the value is freeform so BuildOptions won't be called for placeholders.
            _ => opts,
        };
    }

    private static ExpressionBodyStyle ParseExprBody(string value) => value switch
    {
        "true" => ExpressionBodyStyle.Always,
        "when_on_single_line" => ExpressionBodyStyle.WhenOnSingleLine,
        _ => ExpressionBodyStyle.AsWritten,
    };
}
